name: Update GitHub Profile README

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install Dependencies
        run: pip install requests

      # Run the update script
      - name: Update README Theme
        id: update-script
        run: python update_readme_theme.py
        # No need for shell specification - GitHub handles it

      # Commit changes if needed
      - name: Commit and Push Changes
        if: steps.update-script.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "docs: Update README theme based on GitHub streak" || exit 0
          git push
